# Generated by Django 3.0.7 on 2020-06-14 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorship',
            name='sponsor',
            field=models.ForeignKey(db_column='sponsor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.Sponsor'),
        ),
        migrations.AddField(
            model_name='application',
            name='applicant',
            field=models.ForeignKey(db_column='applicant_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.Student'),
        ),
        migrations.AddField(
            model_name='application',
            name='sponsorship',
            field=models.ForeignKey(db_column='sponsorship_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='applications.Sponsorship'),
        ),
    ]
