# Generated by Django 3.0.7 on 2020-06-14 11:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(default=uuid.UUID('87ac9096-4b04-43e7-aec2-424809ca99f4'), unique=True)),
                ('name', models.CharField(default='No name', max_length=40)),
            ],
            options={
                'db_table': 'schools',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.UUIDField(auto_created=True, default=uuid.uuid4, unique=True)),
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(default='No name', max_length=200)),
                ('school', models.ForeignKey(db_column='school_id', on_delete=django.db.models.deletion.CASCADE, to='schools.School', to_field='school_id')),
            ],
            options={
                'db_table': 'courses',
            },
        ),
    ]
