# Generated by Django 3.0.7 on 2020-06-14 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(default='4a8ce78e-6e75-420c-bb4a-ad14b956babd')),
                ('name', models.CharField(default='No name', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('course_id', models.UUIDField(default='79dbdd18-f474-4b74-b882-8cc60d7fcc1f')),
                ('name', models.CharField(default='No name', max_length=200)),
                ('school', models.ForeignKey(db_column='school_id', on_delete=django.db.models.deletion.CASCADE, to='schools.School')),
            ],
        ),
    ]
