# Generated by Django 3.0.7 on 2020-06-14 09:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='sponsor_id',
            field=models.UUIDField(default=uuid.UUID('81074b3f-3af2-423c-ba1f-2d8d4c1411a2'), unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.UUIDField(default=uuid.UUID('256e1890-5b72-43ec-b354-bcb7f1a876f0'), unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('6e263910-2441-4fd3-bdfb-0ae94d301056'), unique=True),
        ),
    ]
